### ISSUE TITLE
Negation not working?

### ISSUE THREAD

**Issue by dalgard** [gruntjs/grunt-contrib-clean#15]
The following deletes all files in the folder, _including_ main.min.css - shouldn't that file have been negated and thus left behind?

```
clean: [
  "dist/css/**",
  "!dist/css/main.min.css"
]
```

**Comment by jahooma** [comment]
It would be really helpful if cowboy's explanation could be added to the npm readme for grunt-contrib-clean. As it is now, most every person that uses clean will waste ~20 minutes figuring out it doesn't work as expected. Even a small note in the readme would go a long way.

**Comment by shama** [comment]
@jahooma Patches welcome.
