### ISSUE TITLE
Cannot delete files outside the current working directory.

### ISSUE THREAD

**Issue by michaelBenin** [gruntjs/grunt-contrib-clean#29]
grunt clean:development

Running "clean:development" (clean) task

Cleaning "../js"...Warning: Cannot delete files outside the current working directory. Use --
force to continue.

Is there a setting in the config to allow this or possible future feature?

**Comment by danielecr** [comment]
it is closed, but I want to rein-force that going out of directory require options.force = true, even if it is options.["no-write"] == true

**Comment by Schlammsuhler** [comment]
Then could you please provide the option force in the examples? People wouldn't have problems finding it and immediately know how to write it, this is where i failed.

**Comment by nguillaumin** [comment]
My 2c is that it would be useful to provide what the current working directory is, and what files we were trying to delete in the error message. E.g. `Cannot delete files 'bad/*.js' outside the current working directory '/path/to/cwd'. Use --force to continue.`

The list of files is printed with `--verbose`, but not the current working directory which makes it difficult to diagnose.

**Comment by clemens-tolboom** [comment]
I haven't touched the clean task for a year but now it gives this message. Huh?!? I had new OS install + node so digging deeper this message is not from grunt-clean but core

```js
node_modules/grunt/lib/grunt/file.js:354
  // Only delete cwd or outside cwd if --force enabled. Be careful, people!
  if (!options.force) {
    if (file.isPathCwd(filepath)) {
```

which has call to

**Comment by clemens-tolboom** [comment]
In node_modules/grunt/lib/grunt/file.js:424 exports.doesPathContain compares `/Users/clemens/Documents/project` with  `../../project` which does not match.

Is this a OSX problem?

**Comment by clemens-tolboom** [comment]
Problem solved by upgrading node js to 5.8.0.

```bash
ls /usr/local/Cellar/node/5.
5.2.0/  5.4.0/  5.5.0/  5.7.0/  5.8.0/
```

**Comment by semanser** [comment]
I get the same error, but update nodejs to 5.8 solve my problem.

**Comment by wacky6** [comment]
Upgrade to node.js 5.9.0 solved the problem

**Comment by shanecarmody** [comment]
Thanks @clemens-tolboom, that solved it for me too.

**Comment by GimliLongBow** [comment]
Updated to node 5.9.1 solved it for me too!

**Comment by marco-silva0000** [comment]
what other side effects could the force flag cause?

**Comment by HolgerJeromin** [comment]
Changing the message to
```js
grunt.fail.warn('Cannot delete files "' + filepath + '" outside the current working directory: ' + process.cwd());
```
would be so helpful and even consistent to the output a few lines below:
```js
grunt.fail.warn('Unable to delete "' + filepath + '" file (' + err.message + ').', err);
```
