### ISSUE TITLE
Keep getting ENOTEMPTY error. Unable to delete directories.

### ISSUE THREAD

**Issue by Saturate** [gruntjs/grunt-contrib-clean#34]
I am having trouble deleting my dirs when running `grunt-contrib-clean` I get this output

```
Running "clean:dist" (clean) task
Verifying property clean.dist exists in config...OK
Files: .tmp, dist -> dist
Options: force, no-write=false
Cleaning .tmp...ERROR
Warning: Unable to delete ".tmp" file (ENOTEMPTY, directory not empty 'C:\Path\.tmp'). Use --force to continue.

Aborted due to warnings.
```

This is my grunt config:

```
clean: {
    options: { force: true },
    dist: ['.tmp', 'dist']
},
```

Is there anything that I can do to fix this issue?
#### System information
- Windows 7
- Node version: 0.10.17
- Grunt version: 0.4.1
- Task version: 0.5.0

**Comment by mwmwmw** [comment]
My problem was Dropbox. I had to pause syncing before cleaning.

**Comment by dahfazz** [comment]
Thanks a lot mlarcher. I couldn't build my project until reading your comment.

...Windows :(

**Comment by bolora** [comment]
In Windows this is related to windows path 255 character limit.  When you have node modules that are nested deeply the windows path exceeds its limit. If you were to delete the directory by hand in the explorer window you would see the exception triggered and you get a dialog that says something like "the path is too long do you want to proceed with permanently deleting this". When fired from grunt this exception issues an error and grunt stops.

I've been able to somewhat mitigate this issue by identifying problematic node modules and deleting the node_modules directory in those first.

clean: {
            dist: {
                src: ['dist/problem_module_1/node_modules/','dist/problem_module_2/node_modules/', 'dist/'],
                options: {
                    force:true
                }
            }
}

**Comment by androidlinked** [comment]
I have the same problem on Ubuntu14.04 but following way i ha solved it.

    var gulp = require('gulp');
    var rimraf = require('rimraf');

    // delete all files and folders from dist folder
    gulp.task('clean:dist', function (cb) {
        rimraf('./dist/**/*', cb);
    });

**Comment by zxxc** [comment]
I've solved issue for cordova plugins and platforms, by changings like this
 -            plugins: ['plugins'],
-            platforms: ['platforms']
+            plugins: {
+            	files:[
+	            	{
+	            		dot:true,
+	            		src:['plugins/**/*.*', 'plugins/*','plugins']
+	            	}
+            	]
+
+            },
+            platforms: {
+            	files:[
+	            	{
+	            		dot:true,
+	            		src:['platforms/**/*.*', 'platforms/*','platforms']
+	            	}
+            	]
+            }

**Comment by picco** [comment]
To anyone bumping into this - your del task needs to complete before doing other stuff. 
The log needs to look like this:

[23:01:26] Starting 'build'...
[23:01:26] Starting 'clean'...
**[23:01:26] Finished 'build' after 8.35 ms**
[23:01:26] Starting 'default'...

You can solve this with run-sequence module for example:
```
var runSequence = require('run-sequence');

gulp.task('build', () => {
  runSequence('clean', ['server', 'shrinkwrap', 'assets', 'webpack']);
});
```

**Comment by SLdragon1989** [comment]
Some files are being using by another program may cause this problem.

**Comment by jerrylauky** [comment]
@bolora In my case it was the same as yours. Thank you.

**Comment by jaganathanb** [comment]
In my case, unit test was running hence could not delete the files being accessed by karma runner.
