### ISSUE TITLE
Clean All Except?

### ISSUE THREAD

**Issue by pjdicke** [gruntjs/grunt-contrib-clean#38]
This is probably more of a feature request but it might be nice to do clean all except a file or dir?

**Comment by bvanheukelom** [comment]
You also seem to have to use object.files notation. I used an array of paths before and that didn't work.

`		clean: { files:[
			"web/client/**/*.js*",
			"!web/client/libs/**/*.js*",
			 "web/packages/**/*.js*",
			"!web/packages/omm/**/*.js*",
			"web/server/**/*.js*",
			"web/tests/**/*.js*"
		] },`
