### ISSUE TITLE
>> TypeError: Object #<Object> has no method 'registerHelper'

### ISSUE THREAD

**Issue by yngvark** [gruntjs/grunt-contrib-clean#44]
I attempt to run 'grunt clean', with config

```
    clean: {
      folderOne: 'dist/**/*.*'
    },
```

... but I keep getting this error:

> > TypeError: Object #<Object> has no method 'registerHelper'

I have Grunt 0.4.1

**Comment by cdaringe** [comment]
+1, yep :/
