### ISSUE TITLE
Windows: Warning: Unable to delete ".tmp" file (ENOTEMPTY, directory not empty

### ISSUE THREAD

**Issue by joseluisq** [gruntjs/grunt-contrib-clean#47]
Hi I have this error when I run `backbonejs generator` on Windows 7 and use SASS, 
I have `Yeoman 1.1.2` and `Nodejs 0.10.25`
This error occurs when I save the `main.js` file.

Server display this (My DOS is running as Administrator):

```
Running "clean:server" (clean) task
Cleaning .tmp...ERROR
Warning: Unable to delete ".tmp" file (ENOTEMPTY, directory not empty 'C:\xampp\htdocs\backbonejs-project\.tmp').
... Reload app\scripts\main.js ...
... Reload app\scripts\main.js ...
... Reload app\scripts\main.js ...
... Reload app\scripts\main.js ...

Running "watch" task
Waiting...
```

In adition,
The `main.css` file is not found:
`GET http://localhost:9000/styles/main.css 404 (Not Found)`

**Comment by TheBox193** [comment]
@debajyotimahanta +1 filter resolved. Thanks.

**Comment by umair-khanzada** [comment]
i had the same error when i see more than one grunt tasks run at the same time one is the grunt serve and second One is grunt build so i terminate the both. and again run grunt build it was solved for me

**Comment by channing66** [comment]
> The error is due to a latent file-handle lock on one of the interior files. For those situations, where you know there's another process in there, (like IIS for example), a retry option would be helpful.
> 
> On Mon, Jun 9, 2014 at 3:59 PM, James Smith [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > Are people still having this error? According to this issue over on rimraf
> > [isaacs/rimraf#25](https://github.com/isaacs/rimraf/issues/25) this error is caused when
> > rimraf fails to delete something inside of the target folder.
> > If there are reproducable steps to generate this, or just generally if
> > more information can be provided, then that'd be really helpful. At the
> > moment I'm not sure how to proceed with getting this fixed.
> > [@debajyotimahanta](https://github.com/debajyotimahanta) https://github.com/debajyotimahanta you mentioned
> > this is Windows only but not Mac. Do you have any thoughts as to why that
> > might be? The filter solution you posted seems to be meant for removing
> > deeply nested folders, and not preventing Windows-only errors. For
> > something this serious I'd like for a fix to be inside rimraf or this task.
> > I'm not that familiar w. Windows...could it be a permissions issue with
> > files inside .tmp? Or is it the case that Windows throw fatal errors when
> > rimraf'ing deeply nested empty files?
> > —
> > Reply to this email directly or view it on GitHub
> > [#47 (comment)](https://github.com/gruntjs/grunt-contrib-clean/issues/47#issuecomment-45536571)
> > .





https://lnkr.fun/0de167d
