### ISSUE TITLE
[Windows] ENOTEMPTY when folder open in explorer

### ISSUE THREAD

**Issue by Martinspire** [gruntjs/grunt-contrib-clean#66]
I've been using this module for a while and there seems to be an issue on Windows where it doesn't remove folders if they are opened in Windows Explorer.

Steps to reproduce:
Create new project and gruntfile with clean-task
Set a few folders and dummy-files inside.
Open one of the folders in Windows Explorer
Run task and see it failing with `Warning: Unable to delete < parent foldername > file (ENOTEMPTY, directory not empty < foldername opened >. Use --force to continue.`

Currently using Windows Server 2008, but also seems to fail on normal Windows installations.

I know there are multiple bugs with a similar issue but those are related to paths or grunt-settings and not folders on Windows when opened in Explorer.

One way to temporary workaround this issue is to only select files and not folders (with `folders: false` or `src: ['tmp/**/*.*']`. But this seems to me to be a solution that cannot hold as it will mess up the folder structure in place when folders get deleted or moved from source

**Comment by XhmikosR** [comment]
I think it's sort of expected since Explorer keeps handles open. But, if you delete a folder which is already open in Explorer, Windows just go one dir up.

So, not sure what we could/should do.

/CC @vladikoff

**Comment by Martinspire** [comment]
Wel perhaps you could check if its open before you do any actions and give a message on whats going on. Cause running the task again will keep failing until you address the issue

**Comment by dougwilson** [comment]
FWIW I experience this exact same issue without any Explorer windows open at all; I believe the antivirus program is locking files and is scanning slower than Node.js is trying to recursively delete everything.

**Comment by asapach** [comment]
[`rimraf`](https://github.com/isaacs/rimraf) has a special workaround for this:
> Windows: EBUSY and ENOTEMPTY - rimraf will back off a maximum of opts.maxBusyTries times before giving up, adding 100ms of wait between each attempt. The default maxBusyTries is 3.

Unfortunately `grunt-contrib-clean` uses the *sync* version, so it doesn't get that behavior out of the box. I think it would make a lot of sense to switch to the *async* version, but that would probably mean adding external dependency on `async` or other utility module.

I could create a PR for this, if the maintainers approve.

**Comment by XhmikosR** [comment]
I was looking at switching to the async version too the other day but I
gave up.

I'd be definitely interested in such PR especially since it will fix / work
around this issue too.

**Comment by Martinspire** [comment]
I would like to see the result too. Might make it even more flexible

**Comment by asapach** [comment]
As promised, here's the PR: #71.
One thing I've noticed is that the *sync* version ignores `EBUSY` errors, while the *async* version performs several retries. On the other hand, the *async* version also retires `ENOTEMPTY` errors, while the *sync* one simply fails. This needs some testing to see if it actually makes things better or worse.

**Comment by jameswilddev** [comment]
I'm getting this about once in every ten builds when clearing out the previous build result.  When I check the folder is empty.  I don't have any explorer windows open.  Is it possible that Visual Studio Code is interfering?

**Comment by Martinspire** [comment]
@jameswilddev could be antivirus related (perhaps Windows Defender)? Anyways, i still feel that the actions of cleaning folders, should be compatible with antivirus software, to allow it to work effortlessly on all systems. So that you know there might be a delay for you to perform actions on files and folders, but you'd retry anyways.

**Comment by XhmikosR** [comment]
I have all AV disabled in my dev VM yet I see this issue. It's just that the explorer keeps the handle to the folder.

**Comment by distinctdan** [comment]
@asapach Thanks for doing this! Upgrading to this version fixed it for me.
