### ISSUE TITLE
Feature request: Use dest paths if specified

### ISSUE THREAD

**Issue by errorx666** [gruntjs/grunt-contrib-clean#68]
I am trying to delete `.js` files if and only if a corresponding `.ts` file exists.

My project uses TypeScript but also several referenced libraries that are plain JavaScript.  It is assumed that if a TS file exists with the same name as a JS file, that file is the compiled output of the TS file and should be cleaned; if such a file does not exist, then the file is simply a handwritten JavaScript source file and should not be cleaned.

I thought I could write my rule like this:
```
clean: {
	js: {
		expand: true,
		cwd: 'js',
		src: [ '**/*.ts' ],
		ext: 'js'
	}
}
```

That is: select all files matching `**.ts` under the `js` directory, and then change the extension to `js` and target that file.  The task, however, seems to ignore the "dest" paths and only look at "src."

I've been able to workaround with this code:
```
clean: {
	js: [ grunt.file.expandMapping( [ '**/*.ts' ], 'js', {
		ext: '.js'
	} ).map( function( m ) { return m.dest; } ) ]
}
```

This does not seem like a supported scenario but I can't be the first with requirements like these.

**Comment by sindresorhus** [comment]
This task is for cleaning files, not doing other unrelated things. Use a rename task if you need to do that.

**Comment by errorx666** [comment]
Please read more closely.  This issue is not for renaming.  It's for cleaning output files.

**Comment by sindresorhus** [comment]
That's not how this task works or should work.
