### ISSUE TITLE
It is possible to clean the Gruntfile

### ISSUE THREAD

**Issue by ariporad** [gruntjs/grunt-contrib-clean#74]
Hello!

Last night, I found out the hard way that it is 100% possible to clean the gruntfile. It seems like this behavior is a bug, and could be fixed by simply ignoring "Gruntfile.js" as an argument.

Thanks!

**Comment by Herve-M** [comment]
Was you using a filter like this : *.* ?

**Comment by sateffen** [comment]
I don't see, why this should be a bug?

You told the system to delete everything and, to be fair, the gruntfile is part of this. So the system just does what you've orded it to do.

To be honest, I've expected this behaviour, and I think this behaviour is the expected one.

**Comment by shama** [comment]
We take minimal precautions when it comes to deleting your entire file system (`force` is required outside of the `cwd`). But if your pattern matches your own Gruntfile, it will delete it as expected.
