### ISSUE TITLE
publish latest version to npm for Node v5 support

### ISSUE THREAD

**Issue by homeyer** [gruntjs/grunt-contrib-clean#81]
`master` works fine with Node v5, but what's currently published to npm doesn't. `ENOENT` error in `rimraf`.

[This commit](https://github.com/gruntjs/grunt-contrib-clean/commit/c1d03792db8c25bd01c05697ada196c89a07e694) fixed it (the dep change for rimraf), so we just need to publish the latest and everything should be good to go.

**Comment by vladikoff** [comment]
Done

**Comment by homeyer** [comment]
:+1:
