### ISSUE TITLE
Problem with cordova

### ISSUE THREAD

**Issue by furyscript** [gruntjs/grunt-contrib-clean#84]
```
Running "clean" task
Running command: /home/davide/projects/mayapp.it/mobile/platforms/ios/cordova/clean 

>> xcodebuild was not found. Please install version 4.6.0 or greater from App Store
>> Error: mobile/platforms/ios/cordova/clean: Command failed with exit code 2
Warning: Task "clean" failed. Use --force to continue.

Aborted due to warnings.
```
I have this problem when I run clean task... I have Linux Mint so I don't have xcodebuild... How can I fix it?

**Comment by shama** [comment]
Sorry I don't think that issue is with this plugin. We don't do anything with `xcodebuild` and it's likely coming from some other Cordova task. You may want to ask the Cordova folks.
