### ISSUE TITLE
node 5.7.0 – Warning: Cannot delete files outside the current working directory.

### ISSUE THREAD

**Issue by m99coder** [gruntjs/grunt-contrib-clean#85]
Hi guys,

I’m experiencing an issue with the new node 5.7.0.

```javascript
// Gruntfile.js
grunt.initConfig({
	clean: {
		test: {
			src: ['coverage']
		}
	}
});
```

```bash
$ grunt test:clean --verbose
/* ... */
Running "clean:test" (clean) task
Verifying property clean.test exists in config...OK
Files: coverage
Options: force=false, no-write=false
ERROR
Warning: Cannot delete files outside the current working directory. Use --force to continue.

$ node -v && npm -v
v5.7.0
3.7.3
```

It work fine before the node update and I don’t get why the given `coverage` directory should be outside of working directory. `Gruntfile.js` and `coverage` directory are at the same level. The exact same level I’m calling `grunt test:clean` in.

If you need further more verbose output let me know.

**Comment by timvancleef** [comment]
I'm having the same issue.
Maybe it has something to do with the `force` option check in the clean task itself:

```
// Only delete cwd or outside cwd if --force enabled. Be careful, people!
if (!options.force) { ... }
```

Shouldn't that be `if (options.force)` ?

**Comment by timvancleef** [comment]
Having the same issue.
There seems to be a problem with nodejs' `path.relative()` function.
With Node v4.3.1 `path.relative('a/b/c', 'a/b')` returns `..`
Whereas with Node v5.7.0 it returns `../c`.
Therefore the [`isPathInCwd`](https://github.com/gruntjs/grunt-contrib-clean/blob/master/tasks/clean.js#L27) check in the clean task itself fails.

**Comment by mscdex** [comment]
@timvancleef For me `node -pe "require('path').relative('a/b/c', 'a/b')"` on node v5.7.0 outputs `../../b` and *not* `../c`.

**Comment by timvancleef** [comment]
@mscdex oh you are right.
Noetheless the important/problematic part is the `b`, because `isPathInCwd` checks for word characters (`/w+/`).

**Comment by shama** [comment]
Related failing test: https://travis-ci.org/gruntjs/grunt-contrib-clean/jobs/110697189 Nice research you all :)

**Comment by spdaly** [comment]
+1

**Comment by shian48263** [comment]
+1 on Mac

**Comment by shama** [comment]
If you want safety, I recommend going with Node v4.3.1 until a fix is released.

**Comment by gneatgeek** [comment]
FWIW, I haven't observed any issues with versions prior to 5.7.0 (on 5.6.0 currently).

**Comment by vbarbarosh** [comment]
Have the same issue.

    $ node --version
    v5.7.0
    $ node -pe 'require("path").relative("/aa/bb/cc/dd", "/aa/bb/cc")'
    ../../cc

    $ node --version
    v5.0.0
    $ node -pe 'require("path").relative("/aa/bb/cc/dd", "/aa/bb/cc")'
    ..

**Comment by m99coder** [comment]
The node team already fixed it with this commit https://github.com/nodejs/node/commit/3a331b66f8000f2a38e9e98810a4a92a6b3a641d

**Comment by XhmikosR** [comment]
Node.js 5.7.1 is out with the relevant fixes.

**Comment by dcdeiv** [comment]
Hmm same problem here:

```
$ node --version
v8.9.4
$ npm --version
6.2.0
```
