### ISSUE TITLE
"Cannot delete files outside the current working directory" thrown for folder in cwd

### ISSUE THREAD

**Issue by RickyRomero** [gruntjs/grunt-contrib-clean#86]
grunt-contrib-clean 1.0.0
grunt-cli v0.1.13
grunt v0.4.5

No idea what's going on here.  Here's the command I'm running:
`./node_modules/grunt-cli/bin/grunt --debug --verbose build`

Here's the truncated output:

    Running "clean:everything" (clean) task
    [D] Task source: /Users/r/Dropbox/Personal/Projects/rickyromero.com/node_modules/grunt-contrib-clean/tasks/clean.js
    Verifying property clean.everything exists in config...OK
    Files: build/about, build/android-chrome-144x144.bd5c6909.png, build/android-chrome-192x192.9d88696c.png, build/android-chrome-36x36.4e9f2cbd.png, build/android-chrome-48x48.476e6666.png, build/android-chrome-72x72.9dd54f13.png, build/android-chrome-96x96.0be028b0.png, build/apple-pinned-tab-16x16.cc7920d6.svg, build/apple-touch-icon-114x114.f8945fc2.png, build/apple-touch-icon-120x120.dfe2b43c.png, build/apple-touch-icon-144x144.90984226.png, build/apple-touch-icon-152x152.04ddc6aa.png, build/apple-touch-icon-180x180.2a938de0.png, build/apple-touch-icon-57x57.4dc383f0.png, build/apple-touch-icon-60x60.5b378e5b.png, build/apple-touch-icon-72x72.17da9645.png, build/apple-touch-icon-76x76.b5d1f76a.png, build/apple-touch-icon-precomposed.png, build/apple-touch-icon.png, build/articles, build/browserconfig.xml, build/favicon-16x16.72804660.png, build/favicon-194x194.4dddf9d9.png, build/favicon-32x32.04e0de92.png, build/favicon-96x96.f9dfec85.png, build/favicon.ico, build/fonts, build/icons-and-illustration, build/images, build/index.html, build/intuit, build/manifest.1e6957dc.json, build/mstile-144x144.png, build/mstile-150x150.png, build/mstile-310x150.png, build/mstile-310x310.png, build/mstile-70x70.png, build/openemu, build/photos, build/robots.txt, build/scripts, build/shutup, build/styles, build/widgets, build/yahoo
    Options: force=false, no-write=false
    /Users/r/Dropbox/Personal/Projects/rickyromero.com
    ERROR
    Warning: Cannot delete files outside the current working directory. Use --force to continue.

    Aborted due to warnings.

(Line 6 in that output was added by me, adding `grunt.log.writeln(process.cwd());` to clean.js.)

Gruntfile:

    workPath: 'build',

    [...]

    clean: {
        everything: {
            files: [{
                src: ['<%= workPath %>/*']
            }]
        },
        concat: {
            files: [{
                cwd: '<%= workPath %>',
                src: ['**/*'],
                filter: function (path)
                {
                    var concatFiles = grunt.config.get('concat.generated.files');

                    for (var i in concatFiles)
                    {
                        if (concatFiles[i].src.indexOf(path) !== -1)
                        {
                            console.log('Cleaning: %s', path);
                            return true;
                        }
                    }

                    return false;
                }
            }]
        }
    },

`pwd`:

    Sentinel:rickyromero.com r$ pwd
    /Users/r/Dropbox/Personal/Projects/rickyromero.com

/Users/r/Dropbox/Personal/Projects/rickyromero.com/build is not a symlink.

If I add a cwd property to clean:everything, it doesn't throw an error, but it doesn't delete anything either.

**Comment by vladikoff** [comment]
https://github.com/gruntjs/grunt-contrib-clean/issues/85

**Comment by RickyRomero** [comment]
Thanks, this was driving me up the wall!
